services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_USER=admin
        - DATABASE_PASSWORD=admin
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_NAME=design-accounting-service
    restart: on-failure
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db    
      - DATABASE_PORT=5432
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=design-accounting-service
    ports:
      - "2345:5432"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge