services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=design-accounting-service
    ports:
      - "2345:5432"
    env_file:
      - .env